name: "hr-app-filebeat"
logging.metrics.enabled: false
xpack.monitoring.enabled: false
xpack.security.enabled: false
setup.ilm.enabled: false
setup.template.enabled: false

filebeat.config.inputs:
    - type: docker
      containers.ids: '*'
      containers.stream: stdout
      containers.path: "/var/lib/docker/containers"
      scan_frequency: 1s
      logging.level: debug
      logging.to_files: true
      logging.selectors: ["*"]
      enabled: true
      paths:
        - /logs/logs.log
      fields:
        - service: hr-app
      fields_under_root: true
      json:
        keys_under_root: true
        overwrite_keys: true
        message_key: 'message'
      multiline.pattern: '^\['
      multiline.negate: true
      multiline.match: after
      logging:
        files:
          path: /src/logs
          name: 'hr-app-%{+yyyy.MM.dd}.log'
          keepfiles: 7


output.elasticsearch:
  hosts: ["http://elasticsearch:9200"]
  index: "hr-app-%{+yyyy.MM.dd}"

setup.kibana:
  host: "http://kibana:5601"